# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='desc',
            field=models.CharField(max_length=800, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
    ]
